### ISSUE TITLE
关于LSTM预训练模型准确率的问题

### ISSUE THREAD

**Issue by Cambrainnnnn** [Renovamen/Speech-Emotion-Recognition#1]
非常感谢您公布的代码，极具参考价值。
关于LSTM预训练模型识别准确率的问题，我下载了CASIA的1200条数据，参照SER.py中模型的predict方法，对所有数据进行了测试，发现其中错误识别音频为9个，请问我是哪里测试错误了吗？因为这个准确率似乎超出其他算法效果很多。期待您的回复。

**Comment by Renovamen** [comment]
您好，抱歉我没有太理解您是怎么进行测试的，请问可以再说得清楚一点吗，谢谢。
我是把 CASIA 的数据按 8:2 划分了训练集和测试集，在训练集上训练，在测试集上测试。

（关于准确率，我已经更新了特征提取方式，所有模型的准确率都提升了很多...

**Comment by kyroad** [comment]
您好，哪个模型哪个特征方式在casia数据集表现最好，准确率是多少？谢谢

**Comment by renjie1010** [comment]
您好，感谢您的代码，我出现了”NameError: name 'Sequential' is not defined“这个是什么原因，求帮忙

**Comment by renjie1010** [comment]
准确率我用源代码测试达到了86%+

**Comment by AliceSky** [comment]
> 您好，抱歉我没有太理解您是怎么进行测试的，请问可以再说得清楚一点吗，谢谢。
> 我是把 CASIA 的数据按 8:2 划分了训练集和测试集，在训练集上训练，在测试集上测试。
> 
> （关于准确率，我已经更新了特征提取方式，所有模型的准确率都提升了很多...

您好，可以得到划分数据集得结果吗，因为预测得时候想从测试集里面找语料

**Comment by AliceSky** [comment]
我是把 CASIA 的数据按 8:2 划分了训练集和测试集，在训练集上训练，在测试集上测试。
您好，可以得到划分数据集得结果吗，因为预测得时候想从测试集里面找语料

**Comment by renjie1010** [comment]
谢谢大佬，我今天先试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Renovamen/Speech-Emotion-Recognition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月28日(星期三) 中午11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Renovamen/Speech-Emotion-Recognition] 关于LSTM预训练模型准确率的问题 (#1)





 
我是把 CASIA 的数据按 8:2 划分了训练集和测试集，在训练集上训练，在测试集上测试。
 您好，可以得到划分数据集得结果吗，因为预测得时候想从测试集里面找语料
