### ISSUE TITLE
特征提取问题

### ISSUE THREAD

**Issue by sunnymoon155** [Renovamen/Speech-Emotion-Recognition#10]
您好，想请问提取特征时使用IS10_paraling可以训练和测试，但是使用ComParE_2016提取特征后训练会报错。还有就是特征越多效果越好吗？之前只用过默认的IS10_paraling

**Comment by Renovamen** [comment]
您好，我测试用 ComParE_2016 提取特征并没有什么问题...在训练的时候，`config.py` 里也需要保持 `CONFIG = 'ComParE_2016'`，除此之外我想不到别的需要注意的点...

应该不是特征越多越好，至少我测出来 ComParE_2016 的效果不如 IS10_paraling。

**Comment by Yzing0617** [comment]
> 您好，想请问提取特征时使用IS10_paraling可以训练和测试，但是使用ComParE_2016提取特征后训练会报错。还有就是特征越多效果越好吗？之前只用过默认的IS10_paraling

您好，请问您的opensmile的版本是多少，我的opensmile2.3.0版本打开就闪退，我新下载的opensmile3.0版本用的IS10_paraling可以正常训练，但准确率只有0.146左右，调试很久不知道哪里出了问题，求问您可以把您的运行成功的代码发我一下吗，非常非常感谢您，打扰您了非常抱歉。

**Comment by xiao-xin-1** [comment]
> > 您好，想请问提取特征时使用IS10_paraling可以训练和测试，但是使用ComParE_2016提取特征后训练会报错。还有就是特征越多效果越好吗？之前只用过默认的IS10_paraling
> 
> 您好，请问您的opensmile的版本是多少，我的opensmile2.3.0版本打开就闪退，我新下载的opensmile3.0版本用的IS10_paraling可以正常训练，但准确率只有0.146左右，调试很久不知道哪里出了问题，求问您可以把您的运行成功的代码发我一下吗，非常非常感谢您，打扰您了非常抱歉。

我也是 我用opensmile 的准确率也是0.1几左右 请问这个必须要用opensmile2.3吗 你的准确率有提升了吗
