### ISSUE TITLE
Linux环境下多线程调用predict方法会导致程序假死

### ISSUE THREAD

**Issue by Kiteflyingee** [Renovamen/Speech-Emotion-Recognition#12]
在windows环境下测试没有问题，但是Linux平台同样代码就会假死。 初步是认为删除librosa.mfcc或者替换librosa.load就可以正常运行，原因不明

**Comment by Renovamen** [comment]
用 joblib.Parallel 来做多线程似乎就不会有问题了，至少我试了一下是可以的。

https://stackoverflow.com/questions/55487391/unable-to-use-multithread-for-librosa-melspectrogram
