### ISSUE TITLE
SVM.yaml 不同的音频文件，两次分别识别出的六个纬度的值一模一样

### ISSUE THREAD

**Issue by gaoshangle** [Renovamen/Speech-Emotion-Recognition#13]
Probability:  [0.22524792 0.04913896 0.25739536 0.3261612  0.03909501 0.10296156]
Probability:  [0.22524792 0.04913896 0.25739536 0.3261612  0.03909501 0.10296156]
我是直接用的博主训练好的模型，两次识别的音频不一样但是最后识别出的参数一模一样，请问这种情况是由于什么导致的呐？？

**Comment by Renovamen** [comment]
按说是不该这样的...您要不看看是不是预测的时候读到同一个特征了？

**Comment by gaoshangle** [comment]
已解决
