### ISSUE TITLE
给出的参考模型是在CASIA的完整数据集上训练出来的吗？

### ISSUE THREAD

**Issue by gaoshangle** [Renovamen/Speech-Emotion-Recognition#14]

**Comment by Renovamen** [comment]
不是，是在网上找的 1200 个音频的残缺版上训练出来的，9600 个音频的完整版我们也没有。

**Comment by gaoshangle** [comment]
想问一下，那个识别准确率80%是怎么得来的呐？

**Comment by Renovamen** [comment]
按 8:2 随机分训练集和测试集（没分验证集），在训练集上训练完模型后，拿去测试集上跑一个准确率出来。试了了几次之后发现准确率一般不会低于 80%，于是就这么写上去了...

严谨点的做法应该是 k 折交叉，论文里一般是 5 折交叉，不过我懒得写了 2333....

**Comment by gaoshangle** [comment]
这个准确率也是在基于CASIA数据集(不完整版)上得来的吗？

**Comment by Renovamen** [comment]
对的。在提到的另外三个数据集上也有这个准确率。
