### ISSUE TITLE
请问是否能在Windows上面运行？Opensmile如何在Windows上面安装？

### ISSUE THREAD

**Issue by WestbrookZero** [Renovamen/Speech-Emotion-Recognition#15]

**Comment by Renovamen** [comment]
Opensmile 的文档里给了 Windows 上的安装方法（不过我没试过：
https://github.com/naxingyu/opensmile/blob/master/doc/openSMILE_book.pdf

**Comment by WestbrookZero** [comment]
好的，谢谢，还想麻烦问一下，single_feature.csv是怎么创建的？
运行报错：系统找不到指定的路径。
Traceback (most recent call last):
  File "predict.py", line 66, in <module>
    predict(config, audio_path, model)
  File "predict.py", line 36, in predict
    of.get_data(config, audio_path, config.predict_feature_path_opensmile, train = False)
  File "D:\Projects\Audio\Emotion\SER\Speech-Emotion-Recognition-Renovamen\extract_feats\opensmile.py", line 140, in get_data
    feature_vector = get_feature_opensmile(config, data_path)
  File "D:\Projects\Audio\Emotion\SER\Speech-Emotion-Recognition-Renovamen\extract_feats\opensmile.py", line 40, in get_feature_opensmile
    reader = csv.reader(open(BASE_DIR + '/' + config.feature_path + 'single_feature.csv','r'))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Projects\\Audio\\Emotion\\SER\\Speech-Emotion-Recognition-Renovamen/features/6-category/single_feature.csv'

**Comment by Renovamen** [comment]
你看看 `D:\Projects\Audio\Emotion\SER\Speech-Emotion-Recognition-Renovamen/features/6-category/` 这个路径存不存在，`single_feature.csv` 会自动在这个路径下创建，但这个路径不存在的话就会报错。

**Comment by WestbrookZero** [comment]
路径存在，但是single_feature.csv不存在。

**Comment by Renovamen** [comment]
`single_feature.csv` 是在 [`extract_feats/opensmile.py`](https://github.com/Renovamen/Speech-Emotion-Recognition/blob/master/extract_feats/opensmile.py) 里创建的：

https://github.com/Renovamen/Speech-Emotion-Recognition/blob/301a7dd5e2ceec804d2600ac58381a9e1a28906a/extract_feats/opensmile.py#L36

要不把路径里的 `/` 都改成 `\` 试试？Linux 跟 Windows 路径里的斜杠是反的，可能是这个问题导致了读不到路径，我写的时候的确没考虑到这个...

**Comment by Renovamen** [comment]
我刚把涉及到路径的操作都用 `os.path.join` 来处理了 (b3c331215375f64b7c9d7010798a1fcf86a17357)。现在应该在 `example.yaml` 里把路径斜杠都改成 `\`（比如 `feature_path: features\6-category`）就行了。

**Comment by WestbrookZero** [comment]
更新了代码还是报错生成失败，
Opensmile extracting...
Opensmile cmd:  cd D:\\InstallPath\\Develop\\opensmile-2.3.0\\bin\\Win32 && ./SMILExtract -C D:\\InstallPath\\Develop\\opensmile-2.3.0\\bin\\Win32\config\IS10_paraling.conf -I D:\Projects\Audio\Emotion\SER\Speech-Emotion-Recognition-Renovamen\test\EP03_seq04_sc132.wav -O D:\Projects\Audio\Emotion\SER\Speech-Emotion-Recognition-Renovamen\features\6-category\single_feature.csv
'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "D:/Projects/Audio/Emotion/SER/Speech-Emotion-Recognition-Renovamen/predict.py", line 66, in <module>
    predict(config, audio_path, model)
  File "D:/Projects/Audio/Emotion/SER/Speech-Emotion-Recognition-Renovamen/predict.py", line 36, in predict
    of.get_data(config, audio_path, config.predict_feature_path_opensmile, train = False)
  File "D:\Projects\Audio\Emotion\SER\Speech-Emotion-Recognition-Renovamen\extract_feats\opensmile.py", line 149, in get_data
    feature_vector = get_feature_opensmile(config, data_path)
  File "D:\Projects\Audio\Emotion\SER\Speech-Emotion-Recognition-Renovamen\extract_feats\opensmile.py", line 46, in get_feature_opensmile
    reader = csv.reader(open(single_feat_path,'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Projects\\Audio\\Emotion\\SER\\Speech-Emotion-Recognition-Renovamen\\features\\6-category\\single_feature.csv'

Process finished with exit code 1

**Comment by WestbrookZero** [comment]
我手动改了路径在命令行里面输入还是会报错：
D:\InstallPath\Develop\opensmile-2.3.0\bin\Win32>SMILExtract_Release -C D:\InstallPath\Develop\opensmile-2.3.0\config\IS10_paraling.conf -I D:\Projects\Audio\Emotion\SER\Speech-Emotion-Recognition-Renovamen\test\EP03_seq04_sc132.wav -O D:\Projects\Audio\Emotion\SER\Speech-Emotion-Recognition-Renovamen\features\6-category\single_feature.csv
(MSG) [2] in SMILExtract : openSMILE starting!
(MSG) [2] in SMILExtract : config file is: D:\InstallPath\Develop\opensmile-2.3.0\config\IS10_paraling.conf
(MSG) [2] in cComponentManager : successfully registered 95 component types.
(MSG) [2] in instance 'lldsink' : No filename given, disabling this sink component.
(MSG) [2] in instance 'lldhtksink' : No filename given, disabling this sink component.
(MSG) [2] in instance 'lldarffsink' : No filename given, disabling this sink component.
(MSG) [2] in instance 'csvsink' : No filename given, disabling this sink component.
(MSG) [2] in instance 'htksink' : No filename given, disabling this sink component.
smilePcm:  Riff: 46464952
  Format: 45564157
  Subchunk1ID: 20746d66
  Subchunk2ID: 61640000
  AudioFormat: 1
  Subchunk1Size: 12smilePcm: bogus wave/riff header or file in wrong format 
  ('D:\Projects\Audio\Emotion\SER\Speech-Emotion-Recognition-Renovamen\test\EP03_seq04_sc132.wav')! 
  (maybe you are trying to read a 32-bit wave file which is not yet supported (new header type...)?)
  (ERROR) [1] in cWaveSource : failed reading wave header from file 
  'D:\Projects\Audio\Emotion\SER\Speech-Emotion-Recognition-Renovamen\test\EP03_seq04_sc132.wav'!

**Comment by Renovamen** [comment]
嗷那就是 `EP03_seq04_sc132.wav` 这个音频的格式有问题，格式不对所以 opensmile 提不出来特征，也就不会创建 `single_feature.csv`，所以[这行代码](https://github.com/Renovamen/Speech-Emotion-Recognition/blob/master/extract_feats/opensmile.py#L46)读不到 `single_feature.csv`，于是就报错了...

打扰了我还没遇到过音频格式的问题，所以我也不知道用 MATLAB 能不能把格式转对，抱歉...

**Comment by WestbrookZero** [comment]
好的，谢谢，我使用Matlab重新输出解决了。

**Comment by Renovamen** [comment]
好的，祝贺，那我关 issue 了。

**Comment by WestbrookZero** [comment]
好的，谢谢，顺便还想麻烦问一下，除了CASIA汉语情感语料库以外，还有哪些中文的语音情感数据集?我听了一些CASIA数据集，发现很多音频情绪分类的并不准确。

**Comment by Feng-In** [comment]
> 好的，谢谢，我使用Matlab重新输出解决了。

啊，大佬能不能说下怎么用Matlab输出呀，我也遇到这个问题了

**Comment by ldqfalse** [comment]
我也是遇到这个问题了，大佬解决了吗

**Comment by ldqfalse** [comment]
> > 好，谢谢，我使用Matlab重新输出解决了。
> 
> 啊，大佬不能说下怎么输出呀，我也能用M遇到这个问题了

我也是遇到这个问题了，大佬解决了吗

**Comment by YUZHIWANG-bug** [comment]
> 好的，谢谢，顺便还想麻烦问一下，除了CASIA汉语情感语料库以外，还有哪些中文的语音情感数据集?我听了一些CASIA数据集，发现很多音频情绪分类的并不准确。CHEAVD数据集你那有吗？
大佬您好，请问如何在windows上使用opensmile啊，我是遇到了它的终端命令报错，也是没法生成sinal_feature_csv文件，还有请问如何在matlab上面输出不和规范的音频然后送入模型预测啊

**Comment by xiao-xin-1** [comment]
> Opensmile 的文档里给了 Windows 上的安装方法（不过我没试过： https://github.com/naxingyu/opensmile/blob/master/doc/openSMILE_book.pdf

opensmile好像2.3只有linux版。3.0有win64版。但是我用librosa的时候（在win64下），会报llvmite和librosa的错，搞了半天难道这个项目不能在windows上跑吗？？

**Comment by luzhiyuan25** [comment]
作为一名学者，发现问题很重要，但是不把解决方法分享出来就很外行。

**Comment by dipin808** [comment]
> > Opensmile 的文档里给了 Windows 上的安装方法（不过我没试过： https://github.com/naxingyu/opensmile/blob/master/doc/openSMILE_book.pdf
> 
> opensmile好像2.3只有linux版。3.0有win64版。但是我用librosa的时候（在win64下），会报llvmite和librosa的错，搞了半天难道这个项目不能在windows上跑吗？？

请问Windows上可以跑通吗
