### ISSUE TITLE
使用mlp或者svm训练立刻就结束

### ISSUE THREAD

**Issue by WestbrookZero** [Renovamen/Speech-Emotion-Recognition#16]

**Comment by Renovamen** [comment]
模型应该已经训练好了，只是比较快，因为数据量和特征量就那么点...如果你想它多跑一会儿的话，大概可以考虑把 SVM 或 MLP 的最大迭代次数（`max_iter`）调大一点，或者把数据量或特征量搞大一点...

**Comment by WestbrookZero** [comment]
好的，谢谢，因为只有mlp有max_iter，svm的模型参数里面没有max_iter，是可以硬加max_iter这个参数来调大？除了LSTM、CNN、SVM、MLP 这四种方法以外，是不是只剩下GMM+HMM和DNN+HMM这两种的语音情感识别？还有就是可不可以留微信或者微信群可以互相一起交流学习？

**Comment by Renovamen** [comment]
不止吧，只要能做分类的方法都能往里套，可以去搜一下论文看看他们千奇百怪的方法...

不过我早就没有做这个了，我对它仅有的了解估计也就这个项目里的东西了...所以大概帮不上你的忙，我也没有这方面的微信群...
如果你依然愿意加我微信的话，你把微信号发我邮箱怎么样，我加你？

**Comment by Renovamen** [comment]
我发现你之前似乎在那个已经关掉的 issue 上问数据集的事，对不起我一直没看到...

CHEAVD 我们一直没搞到，似乎是比赛的时候给选手用的，理论上可以找数据集论文的作者要，不过我给他们发过邮件但没人理我...你可以也去试一下，论文：[CHEAVD: a Chinese natural emotional audio–visual database](http://www.speakit.cn/Group/file/2016_CHEAVD_AIHC_SCI-Ya%20Li.pdf)

我记得还有些论文也声称他们提出了中文数据集，但数据集没有公开，你也可以搜一下论文，然后试试找作者要...

**Comment by WestbrookZero** [comment]
好的，没事，谢谢啦！已经给您发邮件了！
