### ISSUE TITLE
请问能提供一下CASIA数据集吗

### ISSUE THREAD

**Issue by DengMiao55** [Renovamen/Speech-Emotion-Recognition#17]
你好，请问能提供一下CASIA数据集吗。

**Comment by DengMiao55** [comment]
@Renovamen

**Comment by JanweiCen** [comment]
同求数据集

**Comment by Renovamen** [comment]
CASIA 9600 个音频的完整版我们也没有，似乎是收费的，要去跟中科院买授权（如果感兴趣的话，可以看看这里：

http://www.chineseldc.org/resource_info.php?rid=76

我们也只有网上找的 1200 个音频的版本，如果依然需要的话，这是百度云链接：

链接:https://pan.baidu.com/s/18VJuhxdf0NuOfMG8hNKG1A 提取码:uu30

里面 6 分类的文件夹是我们已经按情感类别分好类的，3 分类的文件夹是我们随便瞎分的不用去管...

**Comment by haier-1314** [comment]
您好，上述数据集的提取码不对，能再分享下吗？万分感谢
