### ISSUE TITLE
过拟合问题

### ISSUE THREAD

**Issue by chdwlx** [Renovamen/Speech-Emotion-Recognition#18]
你好，我用Mosi数据集跑了贵程序，但是出现了过拟合问题，而且是从一开始训练就过拟合，调整参数后还是过拟合严重。请问您有出现类似问题吗？谢谢

**Comment by Renovamen** [comment]
在文档里提到的数据集上训练的时候，我记得的确可能会出现过拟合，但不至于一开始就那么严重...我没试过 Mosi，所以我也不清楚为啥，抱歉 😂
