### ISSUE TITLE
请教模型和数据集的相关问题

### ISSUE THREAD

**Issue by DongLi520** [Renovamen/Speech-Emotion-Recognition#19]
作者大大您好，我在学习您的代码过程中遇到了一点问题想跟您请教，
1、请问您的模型是基于哪个数据集进行训练的呢？
2、另外关于file.py文件里面的处理数据集的三个函数只有remove可以成功调用运行，另外两个改名和移动没有运行不知道是什么原因？
3、请问方便的话可以提供你file处理之后的数据集吗，谢谢您！
期待您的回复！提前祝您新年快乐！！！

**Comment by Renovamen** [comment]
您好，

1. 我都忘了是在哪个数据集上训练的了，我当时的确应该标注一下这个，非常抱歉...考虑到 config 文件里写的是 casia，大概是在 casia 上训练的吧 😂？
2. 这个问题 issue #9 也提过，但我也不清楚，因为我这边运行是没有问题的。我只能盲猜，如果您用的是 windows 系统的话，大概得把 `/` 改成 `\`？或者是得根据不同数据集的文件夹结构对代码做一些细微的修改？
3. EMODB、CASIA、RAVDESS+SAVEE（我把这俩英文数据集合在了一起）：
    链接: https://pan.baidu.com/s/1AglB5mpD5EcqGGgM_xpsdg  密码: 942e

新年快乐朋友，祝万事顺利 😃

**Comment by DongLi520** [comment]
谢谢您的回复，我看您的readme里提到改进了特征提取方式，请问是进行了拿方面的改进呢


| |
重大生物感知与智能信息处理市重-董丽
|
|
lilidonga520@163.com
|
签名由网易邮箱大师定制
在2021年2月13日 23:54，Xiaohan Zou<notifications@github.com> 写道：

您好，

我都忘了是在哪个数据集上训练的了，我当时的确应该标注一下这个，非常抱歉...考虑到 config 文件里写的是 casia，大概是在 casia 上训练的吧 😂？
这个问题 issue #9 也提过，但我也不清楚，因为我这边运行是没有问题的。我只能盲猜，如果您用的是 windows 系统的话，大概得把 / 改成 \？或者是得根据不同数据集的文件夹结构对代码做一些细微的修改？
EMODB、CASIA、RAVDESS+SAVEE（我把这俩英文数据集合在了一起）：
链接: https://pan.baidu.com/s/1AglB5mpD5EcqGGgM_xpsdg 密码: 942e

新年快乐朋友，祝万事顺利 😃

**Comment by Renovamen** [comment]
改进是指相比[第一版代码](https://github.com/Renovamen/Speech-Emotion-Recognition/blob/First-Version/Utilities.py#L59)而言，这一版代码提取的特征要多一些，具体可以参考[这里](https://github.com/Renovamen/Speech-Emotion-Recognition/blob/master/extract_feats/librosa.py#L16)和 [Opensmile 特征集的说明](https://audeering.github.io/opensmile/get-started.html#extracting-features-for-emotion-recognition)。

**Comment by DongLi520** [comment]
好的，我看作者大大您有做过其他论文代码复现的总结，请问您有复现成功过这篇论文的代码吗《3-D Convolutional Recurrent Neural Networks With Attention Model for Speech Emotion Recognition》？


| |
重大生物感知与智能信息处理市重-董丽
|
|
lilidonga520@163.com
|
签名由网易邮箱大师定制
在2021年2月14日 17:33，Xiaohan Zou<notifications@github.com> 写道：

改进是指相比第一版代码而言，这一版代码提取的特征要多一些，具体可以参考这里和 Opensmile 特征集的说明。

**Comment by Renovamen** [comment]
我没有复现过这篇，也没有尝试跑过作者开源的代码 😂

**Comment by DongLi520** [comment]
这样啊，好的谢谢您啊


| |
重大生物感知与智能信息处理市重-董丽
|
|
lilidonga520@163.com
|
签名由网易邮箱大师定制
在2021年2月14日 18:03，Xiaohan Zou<notifications@github.com> 写道：

我没有复现过这篇，也没有尝试跑过作者开源的代码 😂
