### ISSUE TITLE
关于测试问题

### ISSUE THREAD

**Issue by XuHunan** [Renovamen/Speech-Emotion-Recognition#2]
您好，我是语音情感识别的学习新手，我想请教您几个问题：
（1）您里面的feauture中分为只有训练集，请问测试集在哪，还是您所写的播放一段音频（那这段音频是随机采集的还是数据库里的）
（2）我在运行的过程中一直出现ImportError: cannot import name 'Train' from 'SER'错误，请问这种出错原因在哪？
期待您的回复，谢谢

**Comment by Renovamen** [comment]
您好，

1. 所有的特征（包括训练集和测试集）都在 feature 里，`Librosa_Feature.py` 和 `Opensmile_Feature.py` 中的这一句是在按 4:1 随机划分训练集和测试集：
    ```bash
    # 划分训练集和测试集
    x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)
    ```

2. 这个问题我也不清楚，没遇到过这样的坑，抱歉。

**Comment by renjie1010** [comment]
第二个问题，你不要from SER import train  你直接import SER 
然后在下面呢代码train改为 SER.train 就ok了

**Comment by XuHunan** [comment]
> 第二个问题，你不要from SER import train  你直接import SER
> 然后在下面呢代码train改为 SER.train 就ok了

您好，目前我在运行这段代码的时候出现很多问题，我能否加一下您的联系方式，向您请教一下？谢谢！

**Comment by renjie1010** [comment]
我也是朋友帮我弄的，我自己也是个小白，现在也有很多问题。

**Comment by pingguo11** [comment]
![image](https://user-images.githubusercontent.com/61868016/80913883-93989b80-8d7a-11ea-88f5-97dd93034e25.png)
![image](https://user-images.githubusercontent.com/61868016/80913898-aa3ef280-8d7a-11ea-8116-8d96166b08ee.png)
为什么会出现这样的错误呢？求助

**Comment by pingguo11** [comment]
> 我也是朋友帮我弄的，我自己也是个小白，现在也有很多问题。

可以加个联系方式向你咨询一下吗

**Comment by angryman123** [comment]
> ![image](https://user-images.githubusercontent.com/61868016/80913883-93989b80-8d7a-11ea-88f5-97dd93034e25.png)
> ![image](https://user-images.githubusercontent.com/61868016/80913898-aa3ef280-8d7a-11ea-8116-8d96166b08ee.png)
> 为什么会出现这样的错误呢？求助

你这个问题我也遇到了，我在命令行中输入也有这样的错误，你试一下直接在程序中给参数赋值试一试

**Comment by angryman123** [comment]
把cmd.py中的参数赋值语句换成

 option = 't'
    model_type =  'lstm'
    model_name = 'LSTM_OPENSMILE'
    load = 1
    feature = 'o'
    # audio = 'Test/happy.wav'
    audio = args.audio if args.audio else 'default.wav'

**Comment by angryman123** [comment]
> ![image](https://user-images.githubusercontent.com/61868016/80913883-93989b80-8d7a-11ea-88f5-97dd93034e25.png)
> ![image](https://user-images.githubusercontent.com/61868016/80913898-aa3ef280-8d7a-11ea-8116-8d96166b08ee.png)
> 为什么会出现这样的错误呢？求助

你试一下不用命令行输入参数，而在cmd.py文件中进行赋值

 option = 't'
    model_type =  'lstm'
    model_name = 'LSTM_OPENSMILE'
    load = 1
    feature = 'o'
    # audio = 'Test/happy.wav'
    audio = args.audio if args.audio else 'default.wav'
