### ISSUE TITLE
训练和测试数据集划分结果

### ISSUE THREAD

**Issue by AliceSky** [Renovamen/Speech-Emotion-Recognition#22]
您好，请问程序中关于随机划分测试和训练数据集，可以查看随机划分得结果吗

**Comment by Renovamen** [comment]
https://github.com/Renovamen/Speech-Emotion-Recognition/blob/1af9b2da7e27f375b069e57de9f043f3868f25a6/extract_feats/opensmile.py#L84

我估摸着 `x_train, x_test, y_train, y_test` 就是随机划分结果？（快一年过去了你应该也不需要这个回复了 😂
