### ISSUE TITLE
pretrained的模型

### ISSUE THREAD

**Issue by inconnu11** [Renovamen/Speech-Emotion-Recognition#25]
请问发布的pretrained的模型是在casia上训练的吗，有在英文数据集上训练的模型吗

**Comment by Renovamen** [comment]
> 请问发布的pretrained的模型是在casia上训练的吗

之前在 https://github.com/Renovamen/Speech-Emotion-Recognition/issues/19#issuecomment-778637024 提到过，我已经忘了，但我猜测是在 casia（网上能找到的 1200 个音频的版本）上训的 😂

> 有在英文数据集上训练的模型吗

没有，但 readme 里提到的英文数据集都不大，很快就能训练完。
