### ISSUE TITLE
现在这套代码还能跑通吗？试了一晚上没有跑通 0.0

### ISSUE THREAD

**Issue by zzZfans** [Renovamen/Speech-Emotion-Recognition#27]
现在这套代码还能跑通吗？试了一晚上没有跑通 0.0

**Comment by Renovamen** [comment]
你的 Python 和 TensorFlow（以及其他库）的版本是多少？如果跟文档和 requirements.txt 里一样的话，理论上是应该能跑通的（至少我能跑通

**Comment by zzZfans** [comment]
> 你的 Python 和 TensorFlow（以及其他库）的版本是多少？如果跟文档和 requirements.txt 里一样的话，理论上是应该能跑通的（至少我能跑通

pip install -r requirements.txt 拉取的，能否把你的跑通工程打包给我，我再试试 zzzfans@qq.com

**Comment by Renovamen** [comment]
已发。

刚刚补了一个缺失的依赖。我又测试了一遍：

- 新建一个 `python=3.8` 的环境
- `pip install -r requirements.txt` 安装依赖
- 按照 [README](https://github.com/Renovamen/Speech-Emotion-Recognition#train) 中的方法整理数据集结构
- [可选] 如果你要用 Opensmile 抽取特征，安装 Opensmile（用 librosa 抽取特征的话则不需要安装 Opensmile）

之后 `preprocess.py`、`train.py` 和 `predict.py` 都是可以跑通的。

**Comment by Yzing0617** [comment]
求问可以把能跑通的工程也发给我一下吗，感谢您1353087495@qq.com
我安装了opensmile2.3.0版本，但它在我的电脑上一打开就闪退，于是安装了opensmile3.0版本，cmd测试可以运行，但调试preprocess.py的时候依然提取不到特征，cmd opensmile里面提取特征的语句之后显示这样的报错configManager: cFileConfigReader::openInput : cannot find input file '../shared/standard_wave_input.conf.inc‘，但我的opensmile安装文件夹里面有这个文件，于是这个问题暂时解决不了了。

**Comment by zzZfans** [comment]
> 求问可以把能跑通的工程也发给我一下吗，感谢您[1353087495@qq.com](mailto:1353087495@qq.com) 我安装了opensmile2.3.0版本，但它在我的电脑上一打开就闪退，于是安装了opensmile3.0版本，cmd测试可以运行，但调试preprocess.py的时候依然提取不到特征，cmd opensmile里面提取特征的语句之后显示这样的报错configManager: cFileConfigReader::openInput : cannot find input file '../shared/standard_wave_input.conf.inc‘，但我的opensmile安装文件夹里面有这个文件，于是这个问题暂时解决不了了。

没有用 opensmile ，用的 librosa，我就是 opensmile 没通。

**Comment by Yzing0617** [comment]
收到，终于跑出结果了，非常感谢您！

**Comment by Lil-pp** [comment]
> 已发。
> 
> 刚刚补了一个缺失的依赖。我又测试了一遍：
> 
> * 新建一个 `python=3.8` 的环境
> * `pip install -r requirements.txt` 安装依赖
> * 按照 [README](https://github.com/Renovamen/Speech-Emotion-Recognition#train) 中的方法整理数据集结构
> * [可选] 如果你要用 Opensmile 抽取特征，安装 Opensmile（用 librosa 抽取特征的话则不需要安装 Opensmile）
> 
> 之后 `preprocess.py`、`train.py` 和 `predict.py` 都是可以跑通的。

你好！在跑predict.py的时候，会出现提示ModuleNotFoundError: No module named 'sklearn.preprocessing.data'  作者有遇到过这个问题吗

**Comment by Yzing0617** [comment]
> 

请问你的opensmile版本是2.3.0的吗，请问你的是在哪里下载的呢？我下载的opensmile2.3.0软件打开就闪退

**Comment by Yzing0617** [comment]
> 今天试了下，opensmile 也可以跑通的。

请问您的opensmile版本是2.3.0吗，我在GitHub上下载的opensmile2.3.0一直闪退，在网上搜索找不到明确的解决方法

**Comment by zzZfans** [comment]
> > 今天试了下，opensmile 也可以跑通的。
> 
> 请问您的opensmile版本是2.3.0吗，我在GitHub上下载的opensmile2.3.0一直闪退，在网上搜索找不到明确的解决方法

官网下载最新版就可以。

**Comment by Yzing0617** [comment]
> > > 今天试了下，opensmile 也可以跑通的。
> > 
> > 
> > 请问您的opensmile版本是2.3.0吗，我在GitHub上下载的opensmile2.3.0一直闪退，在网上搜索找不到明确的解决方法
> 
> 官网下载最新版就可以。

我前阵子运行最新版的opensmile3.0版本，用的IS10_paraling，准确率只有0.146呜呜，最近一直在调试也不知道是哪里的问题，求问您可以帮忙把您运行成功的代码发我以下吗，非常非常非常感谢您，打扰您了非常抱歉

**Comment by zzZfans** [comment]
> > > > 今天试了下，opensmile 也可以跑通的。
> > > 
> > > 
> > > 请问您的opensmile版本是2.3.0吗，我在GitHub上下载的opensmile2.3.0一直闪退，在网上搜索找不到明确的解决方法
> > 
> > 
> > 官网下载最新版就可以。
> 
> 我前阵子运行最新版的opensmile3.0版本，用的IS10_paraling，准确率只有0.146呜呜，最近一直在调试也不知道是哪里的问题，求问您可以帮忙把您运行成功的代码发我以下吗，非常非常非常感谢您，打扰您了非常抱歉

只是运行成功了，没有深究准确率 (*/ω＼*)。

**Comment by Yzing0617** [comment]
> > > > > 今天试了下，opensmile 也可以跑通的。
> > > > 
> > > > 
> > > > 请问您的opensmile版本是2.3.0吗，我在GitHub上下载的opensmile2.3.0一直闪退，在网上搜索找不到明确的解决方法
> > > 
> > > 
> > > 官网下载最新版就可以。
> > 
> > 
> > 我前阵子运行最新版的opensmile3.0版本，用的IS10_paraling，准确率只有0.146呜呜，最近一直在调试也不知道是哪里的问题，求问您可以帮忙把您运行成功的代码发我以下吗，非常非常非常感谢您，打扰您了非常抱歉
> 
> 只是运行成功了，没有深究准确率 (_/ω＼_)。

啊好的好的，麻烦您了，我再自己看看，谢谢您！

**Comment by v-yunbin** [comment]
> > 已发。
> > 刚刚补了一个缺失的依赖。我又测试了一遍：
> > 
> > * 新建一个 `python=3.8` 的环境
> > * `pip install -r requirements.txt` 安装依赖
> > * 按照 [README](https://github.com/Renovamen/Speech-Emotion-Recognition#train) 中的方法整理数据集结构
> > * [可选] 如果你要用 Opensmile 抽取特征，安装 Opensmile（用 librosa 抽取特征的话则不需要安装 Opensmile）
> > 
> > 之后 `preprocess.py`、`train.py` 和 `predict.py` 都是可以跑通的。
> 
> 你好！在跑predict.py的时候，会出现提示ModuleNotFoundError: No module named 'sklearn.preprocessing.data' 作者有遇到过这个问题吗 更新：抱歉打扰了 已解决

遇到相同得问题，请问怎么解决的

**Comment by Jinzeyuu** [comment]
> > 
> 
> > 已发。
> > 刚刚补了一个缺失的依赖。我又测试了一遍：
> > 
> > * 新建一个 `python=3.8` 的环境
> > * `pip install -r requirements.txt` 安装依赖
> > * 按照 [README](https://github.com/Renovamen/Speech-Emotion-Recognition#train) 中的方法整理数据集结构
> > * [可选] 如果你要用 Opensmile 抽取特征，安装 Opensmile（用 librosa 抽取特征的话则不需要安装 Opensmile）
> > 
> > 之后 `preprocess.py`、`train.py` 和 `predict.py` 都是可以跑通的。
> 
> 感谢作者，已跑通（前面自己太笨了(_/ω＼_)）

你好，可以发我一份吗qq1965782319，我在用opensmile提取特征时总是没有结果，不能生成single_feature.csv文件，谢谢！

**Comment by xiao-xin-1** [comment]
> > 
> 
> > 已发。
> > 刚刚补了一个缺失的依赖。我又测试了一遍：
> > 
> > * 新建一个 `python=3.8` 的环境
> > * `pip install -r requirements.txt` 安装依赖
> > * 按照 [README](https://github.com/Renovamen/Speech-Emotion-Recognition#train) 中的方法整理数据集结构
> > * [可选] 如果你要用 Opensmile 抽取特征，安装 Opensmile（用 librosa 抽取特征的话则不需要安装 Opensmile）
> > 
> > 之后 `preprocess.py`、`train.py` 和 `predict.py` 都是可以跑通的。
> 
> 感谢作者，已跑通（前面自己太笨了(_/ω＼_)）

你好你好，可以把博主跑通的项目给我也发一份吗？十分感谢。1714221274@qq.com

**Comment by xiao-xin-1** [comment]
> 已发。
> 
> 刚刚补了一个缺失的依赖。我又测试了一遍：
> 
> * 新建一个 `python=3.8` 的环境
> * `pip install -r requirements.txt` 安装依赖
> * 按照 [README](https://github.com/Renovamen/Speech-Emotion-Recognition#train) 中的方法整理数据集结构
> * [可选] 如果你要用 Opensmile 抽取特征，安装 Opensmile（用 librosa 抽取特征的话则不需要安装 Opensmile）
> 
> 之后 `preprocess.py`、`train.py` 和 `predict.py` 都是可以跑通的。

你好 我是python3.8的环境 也用的是需求.txt的依赖库
在运行plot.py时报错了（见下）
Traceback (most recent call last):
  File "D:/Git/Project/Speech-Emotion-Recognition/utils/plot.py", line 3, in <module>
    import librosa
  File "D:\anaconda3\envs\myenv\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "D:\anaconda3\envs\myenv\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "D:\anaconda3\envs\myenv\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "D:\anaconda3\envs\myenv\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "D:\anaconda3\envs\myenv\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "D:\anaconda3\envs\myenv\lib\site-packages\librosa\util\utils.py", line 9, in <module>
    import numba
  File "D:\anaconda3\envs\myenv\lib\site-packages\numba\__init__.py", line 15, in <module>
    from . import config, errors, _runtests as runtests, types
  File "D:\anaconda3\envs\myenv\lib\site-packages\numba\config.py", line 331, in <module>
    _env_reloader = _EnvReloader()
  File "D:\anaconda3\envs\myenv\lib\site-packages\numba\config.py", line 76, in __init__
    self.reset()
  File "D:\anaconda3\envs\myenv\lib\site-packages\numba\config.py", line 80, in reset
    self.update(force=True)
  File "D:\anaconda3\envs\myenv\lib\site-packages\numba\config.py", line 109, in update
    self.process_environ(new_environ)
  File "D:\anaconda3\envs\myenv\lib\site-packages\numba\config.py", line 255, in process_environ
    ENABLE_AVX = _readenv("NUMBA_ENABLE_AVX", int, avx_default)
  File "D:\anaconda3\envs\myenv\lib\site-packages\numba\config.py", line 117, in _readenv
    return default() if callable(default) else default
  File "D:\anaconda3\envs\myenv\lib\site-packages\numba\config.py", line 251, in avx_default
    cpu_name = ll.get_host_cpu_name()
AttributeError: module 'llvmlite.binding' has no attribute 'get_host_cpu_name'

说没有那个属性，但是我是已经安装了llvmlite这个库的
作者可以发我一份已经跑通的项目吗？1714221274  QQ
