### ISSUE TITLE
关于文件路径问题

### ISSUE THREAD

**Issue by yoonssica** [Renovamen/Speech-Emotion-Recognition#3]
请问在您给出的代码的opensimle_feature.py文件中的第32行代码reader = csv.reader(open(Config.FEATURE_PATH + 'single_feature.csv', 'r'))指向的是什么

**Comment by Renovamen** [comment]
您好，
每当处理一个音频时，Opensmile 会把它的特征和一些属性说明复写到 `Config.FEATURE_PATH + 'single_feature.csv'` 里，`reader = csv.reader(open(Config.FEATURE_PATH + 'single_feature.csv', 'r'))` 是在把该音频的特征从 `single_feature.csv` 里读出来，之后会追加进一个包含所有音频特征的 csv 里。
所以相当于  `Config.FEATURE_PATH + 'single_feature.csv'` 是一个临时的文件，不用去管...
