### ISSUE TITLE
casia数据集使用opensmile进行特征提取不一致的问题

### ISSUE THREAD

**Issue by NLPAN** [Renovamen/Speech-Emotion-Recognition#39]
我对casia数据集使用opensmile进行特征提取，但是发现提取出来的特征和你\features\6-category\opensmile_casia\train.csv不一致，请问是什么原因？谢谢！

**Comment by NLPAN** [comment]
我用的casia数据集也是1200条，感觉应该和你用的数据集是一样的

![1664350932010](https://user-images.githubusercontent.com/33030136/192719166-b830b645-61c6-4fce-970c-8d0722ccf9eb.png)

**Comment by xiao-xin-1** [comment]
请问如何把数据集里这四位同学的数据都用上呢？ 我直接用项目里的代码 报错说找不到angry 需要进行那些修改呢？
