### ISSUE TITLE
有关数据集

### ISSUE THREAD

**Issue by zgzjdx** [Renovamen/Speech-Emotion-Recognition#6]
作者您好：
     能否提供一下CASIA的数据集，万分感谢！

**Comment by Renovamen** [comment]
您好，

CASIA 9600 个音频的完整版我们也没有，我们也只有网上找的 1200 个音频的版本。如果您依然需要的话，这是百度云链接：https://pan.baidu.com/s/18VJuhxdf0NuOfMG8hNKG1A，提取码：uu30

**Comment by zgzjdx** [comment]
收到，感谢您的回信！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Renovamen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 下午2:23
收件人:&nbsp;"Renovamen/Speech-Emotion-Recognition"<Speech-Emotion-Recognition@noreply.github.com&gt;;
抄送:&nbsp;"童逸琦"<371516709@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Renovamen/Speech-Emotion-Recognition] 有关数据集 (#6)





 
您好，
 
CASIA 9600 个音频的完整版我们也没有，我们也只有网上找的 1200 个音频的版本。如果您依然需要的话，这是百度云链接：https://pan.baidu.com/s/18VJuhxdf0NuOfMG8hNKG1A，提取码：uu30
