### ISSUE TITLE
关于模型训练的问题

### ISSUE THREAD

**Issue by 15458wew** [Renovamen/Speech-Emotion-Recognition#7]
您好，看了您的代码受益很多，但是在模型训练的时候我遇到了一些问题。好像模型训练还没有开始就结束了。
刚一开始出现-----------start---------------之后出现一些数字，紧接着出现------------end---------------
然后就结束了。。。
另外我在Models里发现一些.m文件不知道，这是训练好的模型？

期待您的回复。

谢谢
祝好

**Comment by vince9515** [comment]
你好，我在跑代码过程中遇到一些问题，是否可以向你请教一下

**Comment by pingguo11** [comment]
情感识别小白，跑程序也遇到很多问题，可否向您请教一下

**Comment by angryman123** [comment]
您好，在程序运行的过程中我遇到了一些困难，可不可以向您请教一下

**Comment by angryman123** [comment]
在命令行输入训练的命令以后，代码报错
UnboundLocalError: local variable 'model' referenced before assignment
我这里实在不知道要怎么去更改才能改掉错误，烦请指导

**Comment by Renovamen** [comment]
@15458wew 

您好，

如果您用的是 SVM 或 MLP 的话，那模型应该已经训练好了，只是比较快，因为数据量就那么点...后面出现的数字是在测试集上的验证结果。如果你想它多跑一会儿的话，可以考虑把 SVM 或 MLP 的最大迭代次数（`max_iter`）调大一点...

是的 `.m` 是训练好的文件，大概算是我的备份可以忽视掉...

祝好

**Comment by Renovamen** [comment]
> 在命令行输入训练的命令以后，代码报错
> UnboundLocalError: local variable 'model' referenced before assignment
> 我这里实在不知道要怎么去更改才能改掉错误，烦请指导

您好，

似乎很多人都提过这个问题，但我这边的确没出过这个问题，所以我只能盲猜是处理命令行输入时的问题。于是我现在改了改命令行输入部分的代码，如果您现在还在做这个的话，可以考虑再试试还有没有问题？如果还有问题的话，那就不用命令行输入直接调函数吧（更新后的文档里写了怎么直接调函数）...

祝好
