### ISSUE TITLE
识别时数据的问题

### ISSUE THREAD

**Issue by renjie1010** [Renovamen/Speech-Emotion-Recognition#8]
我运行代码什么都没问题，然后自己截取了一个小的语音数据集，时长都是1s，但是识别测试的时候就会报错，语音无法识别，我该怎么办

**Comment by renjie1010** [comment]
是不是只有训练集中出现的语音，才能被用来识别。

**Comment by angryman123** [comment]
> 我运行代码什么都没问题，然后自己截取了一个小的语音数据集，时长都是1s，但是识别测试的时候就会报错，语音无法识别，我该怎么办

你好，我可不可以问一下你怎么运行代码的呢

**Comment by pingguo11** [comment]
> 我运行代码什么都没问题，然后自己截取了一个小的语音数据集，时长都是1s，但是识别测试的时候就会报错，语音无法识别，我该怎么办

可能是你没有转换音频格式，转成wav就可以了

**Comment by Renovamen** [comment]
> > 我运行代码什么都没问题，然后自己截取了一个小的语音数据集，时长都是1s，但是识别测试的时候就会报错，语音无法识别，我该怎么办
> 
> 可能是你没有转换音频格式，转成wav就可以了

是的，我记得我们之前从电视剧里截了些音频然后转成 wav 来测是没问题的。
